
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crypto_wallet_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: crypto_wallet_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: crypto_wallet_production
  username: crypto_wallet
  password: <%= ENV['CRYPTO_WALLET_DATABASE_PASSWORD'] %>